Add goal around reproducibility
redhat-appstudio/architecture pull request #173
Opened 2024-03-12 18:59 UTC by arewm

As much as possible, builds should be driven from source control in order to improve the reproducibility, even if just semantic instead of bit-for-bit reproducibility.

2024-03-12 19:02 UTC, ralphbean approved these changes

2024-03-13 12:21 UTC, scoheb requested changes

2024-03-13 12:21 UTC, scoheb commented on architecture/index.md
> +- Build semantic reproducibile artifacts. Any configuration which has the potential to affect the semantic functionality of a build should be source controlled and associated with the produced artifa
Typo -> reproducible

2024-03-13 12:25 UTC, arewm commented on architecture/index.md
> +- Build semantic reproducibile artifacts. Any configuration which has the potential to affect the semantic functionality of a build should be source controlled and associated with the produced artifa
Thanks, vim. :)

2024-03-13 12:36 UTC, scoheb approved these changes

2024-03-13 12:45 UTC, merged